"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { PLANS, formatPrice, type Plan } from "@/lib/plans";

// ─── helpers ──────────────────────────────────────────────────────────────────

function loadRazorpay(): Promise<boolean> {
  return new Promise((resolve) => {
    if (typeof window !== "undefined" && "Razorpay" in window) return resolve(true);
    if (document.getElementById("rp-sdk")) return resolve(true);
    const s = document.createElement("script");
    s.id = "rp-sdk";
    s.src = "https://checkout.razorpay.com/v1/checkout.js";
    s.onload  = () => resolve(true);
    s.onerror = () => resolve(false);
    document.body.appendChild(s);
  });
}

const GoogleG = () => (
  <svg width="18" height="18" viewBox="0 0 24 24" aria-hidden>
    <path fill="#4285F4" d="M23.49 12.27c0-.79-.07-1.54-.19-2.27H12v4.51h6.45c-.28 1.48-1.13 2.73-2.41 3.57v2.96h3.88c2.27-2.09 3.57-5.17 3.57-8.77z"/>
    <path fill="#34A853" d="M12 24c3.24 0 5.95-1.08 7.93-2.91l-3.88-2.96c-1.08.72-2.45 1.16-4.05 1.16-3.12 0-5.77-2.11-6.71-4.94H1.3v3.1C3.27 21.3 7.31 24 12 24z"/>
    <path fill="#FBBC05" d="M5.29 14.35c-.24-.72-.38-1.48-.38-2.35s.14-1.63.38-2.35V6.55H1.3C.47 8.2 0 10.05 0 12s.47 3.8 1.3 5.45l3.99-3.1z"/>
    <path fill="#EA4335" d="M12 4.77c1.77 0 3.35.61 4.6 1.8l3.44-3.44C17.95 1.19 15.24 0 12 0 7.31 0 3.27 2.7 1.3 6.55l3.99 3.1C6.23 6.82 8.88 4.77 12 4.77z"/>
  </svg>
);

// ─── TOS content ──────────────────────────────────────────────────────────────

const TOS_SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: `By creating a Kunjara OS™ account you confirm that you are at least 18 years old and have the legal authority to enter this agreement on behalf of yourself or your business. If you do not agree to these terms, do not create an account.`,
  },
  {
    title: "2. Description of Service",
    body: `Kunjara OS™ is an AI-powered event operating system that provides proposal generation, budget management, vendor coordination, event logistics, and related services. The platform is operated by Indigo Events & Promotions ("Indigo EP"), Mumbai, Maharashtra, India.`,
  },
  {
    title: "3. Account & Security",
    body: `You are responsible for maintaining the confidentiality of your login credentials. You must notify us immediately at hello@kunjaraos.com of any unauthorized use. We reserve the right to suspend accounts where we detect fraudulent activity, scraping, or misuse.`,
  },
  {
    title: "4. Subscription & Payment",
    body: `Access to Kunjara OS™ requires an active paid subscription. All fees are in Indian Rupees (INR) and subject to 18% GST. Payments are processed securely via Razorpay. Subscriptions renew monthly or annually depending on your selection. You may cancel at any time; no refunds are issued for partial periods. The first payment is due at sign-up.`,
  },
  {
    title: "5. AI Credits & Usage Limits",
    body: `Each plan includes a monthly AI credit allocation. Credits are used when you generate proposals, run AI queries through Atlas X, or use other AI-powered features. Unused credits do not roll over to the next billing period. Additional credit packs may be purchased from the Billing page.`,
  },
  {
    title: "6. Your Content & Data",
    body: `You retain full ownership of all content you create on Kunjara OS™ — proposals, budgets, client information, and event data. By using the platform you grant Indigo EP a limited licence to process and store your content solely to deliver the service. We do not sell, share, or commercially exploit your data.`,
  },
  {
    title: "7. AI-Generated Output",
    body: `Proposals and other content generated by Kunjara OS™ AI features are produced for your use and review. You are responsible for verifying accuracy before sending to clients. Kunjara OS™ makes no warranty that AI output is error-free. You own the final approved proposals; AI-generated drafts do not constitute professional advice.`,
  },
  {
    title: "8. Privacy & Data Protection",
    body: `Your data is governed by our Privacy Policy (kunjaraos.com/privacy) and handled in accordance with the Information Technology Act 2000, IT Rules 2011, and the Digital Personal Data Protection Act 2023 (DPDP Act). Client names and event data are never shared with third parties or used to train AI models.`,
  },
  {
    title: "9. Prohibited Uses",
    body: `You agree not to: (a) resell or sublicense access to the platform; (b) scrape, crawl, or extract data via automated means; (c) use the platform to generate fraudulent proposals or misrepresent services to clients; (d) circumvent subscription gates or credit limits; (e) upload malicious code or attempt to compromise platform security.`,
  },
  {
    title: "10. Limitation of Liability",
    body: `To the maximum extent permitted by applicable law, Indigo EP's total liability for any claim arising out of your use of Kunjara OS™ shall not exceed the fees you paid in the three months preceding the claim. We are not liable for indirect, incidental, or consequential damages including lost revenue or lost event contracts.`,
  },
  {
    title: "11. Modifications to Terms",
    body: `We may update these Terms from time to time. Material changes will be communicated by email or an in-app notice at least 14 days before they take effect. Continued use of the platform after that date constitutes acceptance of the updated Terms.`,
  },
  {
    title: "12. Governing Law & Jurisdiction",
    body: `These Terms are governed by the laws of India. Any dispute shall be subject to the exclusive jurisdiction of the courts of Mumbai, Maharashtra. The platform complies with the Indian IT Act 2000 and DPDP Act 2023.`,
  },
];

// ─── Step indicator ───────────────────────────────────────────────────────────

function StepDots({ step }: { step: 1 | 2 | 3 }) {
  return (
    <div style={{ display: "flex", gap: 8, justifyContent: "center", marginBottom: 36 }}>
      {[1, 2, 3].map((n) => (
        <div
          key={n}
          style={{
            width: n === step ? 24 : 8,
            height: 8,
            borderRadius: 999,
            background: n === step ? "#D4A85F" : n < step ? "rgba(212,168,95,0.5)" : "rgba(255,255,255,0.12)",
            transition: "all 0.3s ease",
          }}
        />
      ))}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function SignupPage() {
  const [step, setStep]           = useState<1 | 2 | 3>(1);

  // Step 1 — account info
  const [name,     setName]     = useState("");
  const [email,    setEmail]    = useState("");
  const [password, setPassword] = useState("");
  const [confirm,  setConfirm]  = useState("");
  const [error,    setError]    = useState<string | null>(null);
  const [loading,  setLoading]  = useState(false);

  // Step 2 — TOS
  const tosRef            = useRef<HTMLDivElement>(null);
  const [tosRead,    setTosRead]    = useState(false);
  const [tosAgreed,  setTosAgreed]  = useState(false);

  // Step 3 — plan & payment
  const [annual,       setAnnual]       = useState(false);
  const [payPlan,      setPayPlan]      = useState<Plan | null>(null);
  const [payLoading,   setPayLoading]   = useState(false);
  const [payError,     setPayError]     = useState<string | null>(null);
  const [processing,   setProcessing]   = useState(false); // post-payment confirmation

  function handleTosScroll() {
    const el = tosRef.current;
    if (!el || tosRead) return;
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 32) setTosRead(true);
  }

  // ── Step 1: Google OAuth ──────────────────────────────────────────────────

  async function handleGoogle() {
    setLoading(true);
    setError(null);
    try {
      const supabase = createClient();
      const { error } = await supabase.auth.signInWithOAuth({
        provider: "google",
        options: {
          redirectTo: `${location.origin}/auth/callback?next=${encodeURIComponent("/onboarding")}`,
        },
      });
      if (error) {
        setError("Could not open Google sign-in. Try email below.");
        setLoading(false);
      }
    } catch {
      setError("Could not reach Google. Check your connection and try again.");
      setLoading(false);
    }
  }

  // ── Step 1 → Step 2: validate fields ────────────────────────────────────

  function handleStep1(e: React.FormEvent) {
    e.preventDefault();
    setError(null);

    if (!name.trim())          return setError("Enter your name.");
    if (!email.trim())         return setError("Enter your email address.");
    if (password.length < 8)   return setError("Password must be at least 8 characters.");
    if (password !== confirm)  return setError("Passwords don't match.");

    setStep(2);
  }

  // ── Step 2 → Step 3: create account then show plans ─────────────────────

  async function handleTosAgree() {
    if (!tosAgreed || !tosRead) return;
    setLoading(true);
    setError(null);

    const res = await fetch("/api/auth/signup", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: name.trim(), email: email.trim(), password }),
    });

    if (!res.ok) {
      const json = await res.json().catch(() => ({}));
      setError(json.error ?? "Could not create account. Try again.");
      setLoading(false);
      setStep(1);
      return;
    }

    setLoading(false);
    setStep(3);
  }

  // ── Step 3: Razorpay payment ─────────────────────────────────────────────

  async function handleSubscribe(plan: Plan) {
    setPayPlan(plan.id as never);
    setPayLoading(true);
    setPayError(null);

    const sdkReady = await loadRazorpay();
    if (!sdkReady) {
      setPayError("Payment gateway failed to load. Check your connection and try again.");
      setPayLoading(false);
      return;
    }

    const orderRes = await fetch("/api/billing/create-order", {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ plan: plan.id, annual }),
    });
    const orderJson = await orderRes.json();
    if (!orderJson.success) {
      setPayError(orderJson.error ?? "Failed to create order. Try again.");
      setPayLoading(false);
      return;
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const rzp = new (window as any).Razorpay({
      key:         process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
      order_id:    orderJson.orderId,
      amount:      orderJson.amount,
      currency:    "INR",
      name:        "Kunjara OS™",
      description: `${plan.name} Plan — ${annual ? "Annual" : "Monthly"}`,
      theme:       { color: "#D4A85F" },
      modal: {
        ondismiss: () => {
          setPayLoading(false);
          setPayPlan(null);
        },
      },
      handler: async (response: {
        razorpay_payment_id: string;
        razorpay_order_id: string;
        razorpay_signature: string;
      }) => {
        setProcessing(true);

        const verifyRes = await fetch("/api/billing/verify", {
          method: "POST",
          credentials: "include",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            razorpay_order_id:   response.razorpay_order_id,
            razorpay_payment_id: response.razorpay_payment_id,
            razorpay_signature:  response.razorpay_signature,
            plan: plan.id,
          }),
        });

        if (verifyRes.ok) {
          (window as Window & { gtag?: (...a: unknown[]) => void }).gtag?.("event", "payment_completed", { plan: "pro", value: plan.price, currency: "INR" });
          window.location.href = "/dashboard";
        } else {
          setPayError("Payment received but verification failed. Contact support@kunjaraos.com with your payment ID.");
          setProcessing(false);
          setPayLoading(false);
        }
      },
    });
    rzp.open();
    setPayLoading(false);
  }

  async function handleFreeStart() {
    setPayPlan("free" as never);
    setPayLoading(true);
    setPayError(null);
    try {
      const res = await fetch("/api/auth/activate-free", { method: "POST", credentials: "include" });
      if (!res.ok) {
        const json = await res.json().catch(() => ({}));
        throw new Error(json.error ?? "Could not activate free plan. Try again.");
      }
      (window as Window & { gtag?: (...a: unknown[]) => void }).gtag?.("event", "sign_up", { method: "email", plan: "free" });
      window.location.href = "/dashboard";
    } catch (e: unknown) {
      setPayError(e instanceof Error ? e.message : "Something went wrong.");
      setPayLoading(false);
    }
  }

  // ─── Render ───────────────────────────────────────────────────────────────

  const cardWidth = step === 1 ? 380 : step === 2 ? 680 : 860;

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "#08080A",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "40px 16px",
      }}
    >
      {/* Logo */}
      <a href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none", marginBottom: 36 }}>
        <svg width="36" height="36" viewBox="0 0 64 64" fill="none">
          <circle cx="32" cy="32" r="29" stroke="#D4A85F" strokeWidth="1.25" opacity="0.35"/>
          <circle cx="32" cy="32" r="29" stroke="#D4A85F" strokeWidth="1.25" strokeDasharray="2 6" opacity="0.5" transform="rotate(-30 32 32)"/>
          <g stroke="#D4A85F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" fill="none">
            <path d="M16 38 C 16 22, 48 22, 48 38"/>
            <path d="M22 38 C 22 48, 32 50, 34 42 C 35 38, 30 36, 30 40"/>
            <path d="M40 40 L 44 46"/>
            <circle cx="40" cy="32" r="1.4" fill="#D4A85F" stroke="none"/>
          </g>
          <circle cx="58" cy="22" r="1.6" fill="#D4A85F"/>
        </svg>
        <span style={{ fontFamily: '"Instrument Serif",Georgia,serif', fontSize: 20, fontStyle: "italic", color: "#F4F1EA", letterSpacing: "-0.01em" }}>
          Kunjara<span style={{ fontFamily: "sans-serif", fontStyle: "normal", fontWeight: 600, fontSize: 14, letterSpacing: "0.04em", marginLeft: 3 }}>OS</span>
        </span>
      </a>

      {/* Card */}
      <div
        style={{
          width: "100%",
          maxWidth: cardWidth,
          background: "#0F0E14",
          border: "1px solid rgba(255,255,255,0.07)",
          borderRadius: 20,
          padding: "40px 36px",
          transition: "max-width 0.4s cubic-bezier(0.2,0.8,0.2,1)",
          boxShadow: "0 24px 60px rgba(0,0,0,0.5)",
        }}
      >
        <StepDots step={step} />

        {/* ══════════════ STEP 1 — Account info ══════════════ */}
        {step === 1 && (
          <>
            <div style={{ textAlign: "center", marginBottom: 28 }}>
              <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700, color: "#F4F1EA", letterSpacing: "-0.02em" }}>
                Create your account
              </h1>
              <p style={{ marginTop: 6, fontSize: 13, color: "rgba(244,241,234,0.5)" }}>
                Start with Google or fill in your details below
              </p>
            </div>

            {/* Google */}
            <button
              type="button"
              onClick={handleGoogle}
              disabled={loading}
              style={{
                width: "100%", display: "flex", alignItems: "center", justifyContent: "center",
                gap: 10, padding: "12px 16px", borderRadius: 10,
                border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.03)",
                color: "#F4F1EA", fontSize: 14, fontWeight: 500, cursor: "pointer",
                fontFamily: "inherit", transition: "border-color 0.15s",
              }}
            >
              <GoogleG />
              {loading ? "Opening Google…" : "Continue with Google"}
            </button>

            <div style={{ display: "flex", alignItems: "center", gap: 12, margin: "20px 0" }}>
              <div style={{ flex: 1, height: 1, background: "rgba(255,255,255,0.08)" }} />
              <span style={{ fontSize: 11, color: "rgba(244,241,234,0.35)", letterSpacing: "0.1em" }}>OR</span>
              <div style={{ flex: 1, height: 1, background: "rgba(255,255,255,0.08)" }} />
            </div>

            <form onSubmit={handleStep1} style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              <input
                type="text"
                autoComplete="name"
                placeholder="Full name"
                aria-label="Full name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                disabled={loading}
                style={inputStyle}
              />
              <input
                type="email"
                autoComplete="email"
                placeholder="you@company.com"
                aria-label="Email address"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                disabled={loading}
                style={inputStyle}
              />
              <input
                type="password"
                autoComplete="new-password"
                placeholder="Password (min 8 characters)"
                aria-label="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={loading}
                style={inputStyle}
              />
              <input
                type="password"
                autoComplete="new-password"
                placeholder="Confirm password"
                aria-label="Confirm password"
                value={confirm}
                onChange={(e) => setConfirm(e.target.value)}
                disabled={loading}
                style={inputStyle}
              />

              {error && <ErrorBox msg={error} />}

              <button type="submit" disabled={loading} style={primaryBtnStyle}>
                Continue →
              </button>
            </form>

            <p style={{ marginTop: 20, textAlign: "center", fontSize: 12, color: "rgba(244,241,234,0.4)" }}>
              Already have an account?{" "}
              <Link href="/login" style={{ color: "#D4A85F", textDecoration: "none" }}>Sign in</Link>
            </p>
          </>
        )}

        {/* ══════════════ STEP 2 — Terms & Conditions ══════════════ */}
        {step === 2 && (
          <>
            <div style={{ textAlign: "center", marginBottom: 24 }}>
              <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700, color: "#F4F1EA", letterSpacing: "-0.02em" }}>
                Terms of Service
              </h1>
              <p style={{ marginTop: 6, fontSize: 13, color: "rgba(244,241,234,0.5)" }}>
                Scroll through and accept to continue
              </p>
            </div>

            {/* Scroll container */}
            <div
              ref={tosRef}
              onScroll={handleTosScroll}
              style={{
                height: 380,
                overflowY: "auto",
                border: "1px solid rgba(255,255,255,0.07)",
                borderRadius: 12,
                padding: "24px 20px",
                background: "rgba(0,0,0,0.2)",
                scrollbarWidth: "thin",
                scrollbarColor: "rgba(212,168,95,0.3) transparent",
              }}
            >
              <p style={{ fontSize: 11, color: "rgba(212,168,95,0.7)", fontFamily: "monospace", letterSpacing: "0.1em", marginTop: 0, marginBottom: 20 }}>
                EFFECTIVE DATE: 27 APRIL 2026 · KUNJARA OS™ BY INDIGO EP · MUMBAI, INDIA
              </p>
              {TOS_SECTIONS.map((s) => (
                <div key={s.title} style={{ marginBottom: 20 }}>
                  <div style={{ fontSize: 12, fontWeight: 700, color: "#D4A85F", marginBottom: 6, letterSpacing: "0.01em" }}>
                    {s.title}
                  </div>
                  <p style={{ fontSize: 13, lineHeight: 1.65, color: "rgba(244,241,234,0.65)", margin: 0 }}>
                    {s.body}
                  </p>
                </div>
              ))}
              <p style={{ fontSize: 12, color: "rgba(244,241,234,0.35)", marginTop: 16, marginBottom: 0 }}>
                Full Privacy Policy: <a href="/privacy" target="_blank" rel="noreferrer" style={{ color: "#D4A85F" }}>kunjaraos.com/privacy</a> ·
                Full Terms: <a href="/terms" target="_blank" rel="noreferrer" style={{ color: "#D4A85F" }}>kunjaraos.com/terms</a>
              </p>
            </div>

            {!tosRead && (
              <p style={{ marginTop: 10, fontSize: 11, color: "rgba(212,168,95,0.6)", textAlign: "center" }}>
                ↓ Scroll to the bottom to continue
              </p>
            )}

            {/* Agree checkbox */}
            <label
              style={{
                display: "flex", alignItems: "flex-start", gap: 12, marginTop: 16,
                cursor: tosRead ? "pointer" : "not-allowed", opacity: tosRead ? 1 : 0.4,
              }}
            >
              <input
                type="checkbox"
                checked={tosAgreed}
                disabled={!tosRead}
                onChange={(e) => setTosAgreed(e.target.checked)}
                style={{ marginTop: 2, width: 16, height: 16, accentColor: "#D4A85F", flexShrink: 0 }}
              />
              <span style={{ fontSize: 13, color: "rgba(244,241,234,0.75)", lineHeight: 1.5 }}>
                I have read and agree to the Terms of Service, Privacy Policy, and DPDP Act compliance
                notice. I am at least 18 years old.
              </span>
            </label>

            {error && <ErrorBox msg={error} style={{ marginTop: 12 }} />}

            <button
              onClick={handleTosAgree}
              disabled={!tosAgreed || !tosRead || loading}
              style={{ ...primaryBtnStyle, marginTop: 16, opacity: (!tosAgreed || !tosRead || loading) ? 0.4 : 1, cursor: (!tosAgreed || !tosRead || loading) ? "not-allowed" : "pointer" }}
            >
              {loading ? "Creating account…" : "Agree & Choose Plan →"}
            </button>

            <button onClick={() => { setStep(1); setError(null); }} style={ghostBtnStyle}>
              ← Back
            </button>
          </>
        )}

        {/* ══════════════ STEP 3 — Plan & Payment ══════════════ */}
        {step === 3 && (
          <>
            {processing ? (
              <div style={{ textAlign: "center", padding: "40px 0" }}>
                <div style={{ fontSize: 28, marginBottom: 16 }}>⏳</div>
                <div style={{ fontSize: 16, fontWeight: 600, color: "#F4F1EA", marginBottom: 8 }}>
                  Confirming your payment…
                </div>
                <div style={{ fontSize: 13, color: "rgba(244,241,234,0.5)" }}>
                  This takes just a moment. Please don't close this tab.
                </div>
              </div>
            ) : (
              <>
                <div style={{ textAlign: "center", marginBottom: 28 }}>
                  <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700, color: "#F4F1EA", letterSpacing: "-0.02em" }}>
                    Choose your plan
                  </h1>
                  <p style={{ marginTop: 6, fontSize: 13, color: "rgba(244,241,234,0.5)" }}>
                    Start free with 2 proposals, or upgrade to Pro for 30/month.
                  </p>
                </div>

                {/* Billing toggle */}
                <div style={{ display: "flex", justifyContent: "center", gap: 8, marginBottom: 28 }}>
                  {([{ v: false, l: "Monthly" }, { v: true, l: "Annual — Save 17%" }] as const).map(({ v, l }) => (
                    <button
                      key={l}
                      onClick={() => setAnnual(v)}
                      style={{
                        padding: "8px 18px", borderRadius: 999, border: "none", cursor: "pointer",
                        fontFamily: "inherit", fontSize: 13, fontWeight: 500, transition: "all 0.2s",
                        background: annual === v ? "#D4A85F" : "rgba(255,255,255,0.06)",
                        color: annual === v ? "#08080A" : "#F4F1EA",
                      }}
                    >
                      {l}
                    </button>
                  ))}
                </div>

                {/* Plan cards */}
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
                  {PLANS.filter((p) => p.id !== "basic").map((plan) => {
                    const price   = annual ? plan.annualPrice : plan.price;
                    const isPro   = plan.highlighted;
                    const isBusy  = payLoading && payPlan === (plan.id as never);
                    return (
                      <div
                        key={plan.id}
                        style={{
                          position: "relative",
                          padding: "28px 24px",
                          borderRadius: 16,
                          border: isPro ? "1px solid rgba(212,168,95,0.4)" : "1px solid rgba(255,255,255,0.07)",
                          background: isPro ? "linear-gradient(180deg,rgba(212,168,95,0.06) 0%,rgba(255,255,255,0.02) 100%)" : "rgba(255,255,255,0.02)",
                          transform: isPro ? "translateY(-4px)" : "none",
                          boxShadow: isPro ? "0 20px 50px -20px rgba(212,168,95,0.3)" : "none",
                        }}
                      >
                        {isPro && (
                          <div style={{
                            position: "absolute", top: -11, left: 20,
                            padding: "4px 12px", borderRadius: 999,
                            background: "#D4A85F", color: "#08080A",
                            fontSize: 10, fontWeight: 700, letterSpacing: "0.12em",
                          }}>
                            MOST POPULAR
                          </div>
                        )}
                        <div style={{ fontSize: 12, color: "rgba(244,241,234,0.55)", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 12 }}>
                          {plan.name}
                        </div>
                        <div style={{ display: "flex", alignItems: "flex-end", gap: 4, marginBottom: 4 }}>
                          <span style={{ fontSize: 16, color: "rgba(244,241,234,0.6)", marginBottom: 8 }}>₹</span>
                          <span style={{ fontFamily: "Georgia,serif", fontSize: 44, lineHeight: 1, color: "#F4F1EA" }}>
                            {price.toLocaleString("en-IN")}
                          </span>
                          <span style={{ fontSize: 13, color: "rgba(244,241,234,0.45)", marginBottom: 8, marginLeft: 4 }}>/mo</span>
                        </div>
                        {annual && (
                          <div style={{ fontSize: 12, color: "#34D399", marginBottom: 10 }}>
                            ₹{(price * 12).toLocaleString("en-IN")}/year
                          </div>
                        )}
                        <div style={{ fontSize: 12, color: "#D4A85F", marginBottom: 16 }}>
                          {plan.proposals} proposals/month
                        </div>
                        <div style={{ height: 1, background: "rgba(255,255,255,0.07)", marginBottom: 16 }} />
                        <ul style={{ listStyle: "none", padding: 0, margin: "0 0 20px", display: "flex", flexDirection: "column", gap: 8 }}>
                          {plan.features.map((f) => (
                            <li key={f} style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "rgba(244,241,234,0.75)" }}>
                              <span style={{ color: "#D4A85F", flexShrink: 0 }}>✓</span>{f}
                            </li>
                          ))}
                        </ul>
                        <button
                          onClick={() => plan.price === 0 ? handleFreeStart() : handleSubscribe(plan)}
                          disabled={payLoading}
                          style={{
                            width: "100%", padding: "12px 16px", borderRadius: 10, border: "none",
                            fontFamily: "inherit", fontSize: 13, fontWeight: 500, cursor: payLoading ? "not-allowed" : "pointer",
                            background: isPro ? "linear-gradient(135deg,#D4A85F,#E5C07B)" : "rgba(255,255,255,0.07)",
                            color: isPro ? "#08080A" : "#F4F1EA",
                            opacity: payLoading ? 0.6 : 1,
                            transition: "all 0.15s",
                          }}
                        >
                          {isBusy ? "Processing…" : plan.price === 0 ? "Start for Free →" : `Subscribe to ${plan.name}`}
                        </button>
                      </div>
                    );
                  })}
                </div>

                {payError && <ErrorBox msg={payError} style={{ marginTop: 16 }} />}

                <p style={{ marginTop: 20, textAlign: "center", fontSize: 11, color: "rgba(244,241,234,0.3)" }}>
                  All prices + 18% GST · Secured by Razorpay · UPI / Card / Net Banking
                </p>
              </>
            )}
          </>
        )}
      </div>

      <p style={{ marginTop: 28, fontSize: 11, color: "rgba(244,241,234,0.25)", textAlign: "center" }}>
        © 2026 Kunjara OS™ by Indigo EP · Mumbai, India
      </p>
    </div>
  );
}

// ─── Small shared styles ──────────────────────────────────────────────────────

const inputStyle: React.CSSProperties = {
  width: "100%",
  padding: "12px 14px",
  borderRadius: 10,
  border: "1px solid rgba(255,255,255,0.1)",
  background: "rgba(255,255,255,0.03)",
  color: "#F4F1EA",
  fontSize: 14,
  fontFamily: "inherit",
  outline: "none",
  transition: "border-color 0.15s",
};

const primaryBtnStyle: React.CSSProperties = {
  width: "100%",
  padding: "13px 16px",
  borderRadius: 10,
  border: "none",
  background: "linear-gradient(135deg,#D4A85F,#E5C07B)",
  color: "#08080A",
  fontSize: 14,
  fontWeight: 600,
  cursor: "pointer",
  fontFamily: "inherit",
  transition: "all 0.15s",
  boxShadow: "0 8px 24px rgba(212,168,95,0.3)",
};

const ghostBtnStyle: React.CSSProperties = {
  width: "100%",
  marginTop: 10,
  padding: "11px 16px",
  borderRadius: 10,
  border: "1px solid rgba(255,255,255,0.08)",
  background: "transparent",
  color: "rgba(244,241,234,0.5)",
  fontSize: 13,
  cursor: "pointer",
  fontFamily: "inherit",
  transition: "all 0.15s",
};

function ErrorBox({ msg, style }: { msg: string; style?: React.CSSProperties }) {
  return (
    <div style={{
      padding: "10px 14px",
      borderRadius: 8,
      border: "1px solid rgba(239,68,68,0.25)",
      background: "rgba(239,68,68,0.08)",
      fontSize: 12,
      color: "#FCA5A5",
      lineHeight: 1.5,
      ...style,
    }}>
      {msg}
    </div>
  );
}
